import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        app: 'var(--color-app-bg)',
        surface: { DEFAULT: 'var(--color-panel)', alt: 'var(--color-panel-raised)' },
        panel: {
          DEFAULT: 'var(--color-panel)',
          header: 'var(--color-panel-header)',
          hover: 'var(--color-panel-hover)',
          active: 'var(--color-panel-active)',
          input: 'var(--color-input-bg)',
          raised: 'var(--color-panel-raised)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          light: 'var(--color-border-light)',
          focus: 'var(--color-border-focus)',
          strong: 'var(--color-border-strong)',
        },
        divider: 'var(--color-divider)',
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          disabled: 'var(--color-text-disabled)',
          accent: 'var(--color-text-accent)',
          muted: 'var(--color-text-muted)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
          pressed: 'var(--color-accent-pressed)',
          muted: 'var(--color-accent-muted)',
        },
        primary: {
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
          muted: 'var(--color-accent-muted)',
        },
        danger: 'var(--color-danger)',
        warning: 'var(--color-warning)',
        success: 'var(--color-success)',
        info: 'var(--color-info)',
        playhead: 'var(--timeline-playhead)',
        label: {
          violet: 'var(--label-violet)',
          blue: 'var(--label-blue)',
          cyan: 'var(--label-cyan)',
          green: 'var(--label-green)',
          yellow: 'var(--label-yellow)',
          orange: 'var(--label-orange)',
          pink: 'var(--label-pink)',
          red: 'var(--label-red)',
        },
      },
      fontFamily: {
        ui: 'var(--font-family)',
        mono: 'var(--font-family-mono)',
      },
      fontSize: {
        'ui-xs': 'var(--font-size-xs)',
        'ui-sm': 'var(--font-size-sm)',
        'ui-md': 'var(--font-size-md)',
        'ui-lg': 'var(--font-size-lg)',
        'ui-xl': 'var(--font-size-xl)',
      },
      spacing: {
        splitter: 'var(--size-splitter)',
        row: 'var(--size-row)',
        toolbar: 'var(--size-toolbar-width)',
        menubar: 'var(--size-menubar-height)',
        'panel-header': 'var(--size-panel-header)',
        'tl-header': 'var(--size-timeline-header)',
        'tl-row': 'var(--size-timeline-row)',
        'outliner-indent': 'var(--outliner-indent)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        panel: 'var(--radius-panel)',
      },
      zIndex: {
        menu: 'var(--z-menu)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        tooltip: 'var(--z-tooltip)',
        dropdown: 'var(--z-dropdown)',
      },
      transitionDuration: {
        fast: 'var(--dur-fast)',
        normal: 'var(--dur-normal)',
        slow: 'var(--dur-slow)',
      },
      transitionTimingFunction: {
        'ease-out-custom': 'var(--ease-out)',
      },
      boxShadow: {
        panel: 'var(--shadow-panel)',
        dropdown: 'var(--shadow-dropdown)',
        modal: 'var(--shadow-modal)',
        tooltip: 'var(--shadow-tooltip)',
        focus: 'var(--shadow-focus)',
      },
      backdropBlur: { xs: '4px' },
      minWidth: { '0': '0' },
      minHeight: { '0': '0' },
    },
  },
  plugins: [],
};
export default config;